module.exports = {
  env: {
    browser: true,
    es6: true,
    "jest/globals": true,
    node: true,
  },
  globals: {
    flushPromises: true,
  },
  extends: [
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "prettier/@typescript-eslint",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
    sourceType: "module",
  },
  plugins: ["react", "import", "jsx-a11y", "jest", "prettier", "@typescript-eslint"],
  rules: {
    "array-callback-return": "warn",
    "arrow-body-style": ["off"],
    "arrow-parens": ["warn", "as-needed"],
    "class-methods-use-this": "warn",
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "never",
      },
    ],
    "consistent-return": "warn",
    "constructor-super": "error",
    "dot-notation": "warn",
    "for-direction": "error",
    "generator-star-spacing": ["off"],
    "getter-return": "error",
    "jsx-no-target-blank": "off",
    "jsx-quotes": ["off"],
    "linebreak-style": ["error", "unix"],
    "max-len": ["off"],
    "new-cap": ["error", { capIsNew: false }],
    "no-alert": "off",
    "no-array-constructor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "warn",
    "no-console": "error",
    "no-const-assign": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-args": "error",
    "no-dupe-class-members": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-else-return": "warn",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "warn",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-lonely-if": "warn",
    "no-mixed-operators": [
      "warn",
      {
        groups: [["&", "|", "^", "~", "<<", ">>", ">>>"], ["&&", "||"]],
        allowSamePrecedence: true,
      },
    ],
    "no-nested-ternary": "warn",
    "no-new-symbol": "error",
    "no-obj-calls": "error",
    "no-octal": "error",
    "no-param-reassign": "warn",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-shadow": "off",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-undef": "warn",
    "no-underscore-dangle": ["off"],
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-labels": "error",
    "no-unused-vars": "off",
    "no-use-before-define": ["warn", { functions: false }],
    "no-useless-constructor": "warn",
    "no-useless-escape": "warn",
    "object-shorthand": "warn",
    "prefer-const": "warn",
    "prefer-template": "warn",
    "quote-props": ["warn", "as-needed"],
    "require-yield": "error",
    "space-before-function-paren": ["warn", { anonymous: "never", asyncArrow: "always", named: "never" }],
    "use-isnan": "error",
    "valid-typeof": "error",
    camelcase: ["error", { ignoreDestructuring: false, properties: "never" }],
    eqeqeq: "warn",
    indent: "off",
    quotes: ["off"],
    semi: ["error", "always"],

    // @typescript-eslint/eslint-plugin rules
    "@typescript-eslint/explicit-function-return-type": ["off"],
    "@typescript-eslint/no-explicit-any": ["off"],
    "@typescript-eslint/indent": [
      "error",
      2,
      {
        flatTernaryExpressions: false,
        ignoredNodes: ["CallExpression", "ConditionalExpression", "LogicalExpression", "JSXElement"],
        SwitchCase: 1,
      },
    ],
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        varsIgnorePattern: "^_",
        argsIgnorePattern: "^_",
      },
    ],

    // eslint-plugin-import rules
    "import/extensions": "off",
    "import/first": "warn",
    "import/no-extraneous-dependencies": ["off"],
    "import/no-unresolved": ["off"],
    "import/prefer-default-export": "off",

    // eslint-plugin-jsx-a11y rules
    "jsx-a11y/alt-text": "warn",
    "jsx-a11y/label-has-for": "warn",
    "jsx-a11y/no-noninteractive-element-interactions": "warn",
    "jsx-a11y/no-static-element-interactions": "warn",

    // eslint-plugin-react rules
    "react/forbid-prop-types": "off",
    "react/jsx-closing-bracket-location": "warn",
    "react/jsx-filename-extension": ["warn", { extensions: [".jsx", ".tsx"] }],
    "react/jsx-indent-props": ["warn", 2],
    "react/jsx-indent": ["warn", 2],
    "react/jsx-no-bind": ["warn", { allowArrowFunctions: true }],
    "react/jsx-no-duplicate-props": "warn",
    "react/jsx-no-target-blank": "warn",
    "react/jsx-uses-vars": "error",
    "react/jsx-wrap-multilines": "warn",
    "react/no-array-index-key": "warn",
    "react/no-did-update-set-state": "warn",
    "react/no-find-dom-node": "warn",
    "react/no-multi-comp": "warn",
    "react/no-string-refs": "warn",
    "react/no-unused-prop-types": "warn",
    "react/prop-types": "off",
    "react/require-default-props": "warn",
  },
};
