repo:
- changed-files:
  - any-glob-to-any-file:
    - "!packages/**/*"
    - "!package.json"
    - "!yarn.lock"

eslint-config-wantedly-typescript:
- changed-files:
  - any-glob-to-any-file: packages/eslint-config-wantedly-typescript/**/*

eslint-config-wantedly:
- changed-files:
  - any-glob-to-any-file: packages/eslint-config-wantedly/**/*

eslint-plugin-use-macros:
- changed-files:
  - any-glob-to-any-file: packages/eslint-plugin-use-macros/**/*

eslint-plugin-wantedly:
- changed-files:
  - any-glob-to-any-file: packages/eslint-plugin-wantedly/**/*

frolint:
- changed-files:
  - any-glob-to-any-file: packages/frolint/**/*

prettier-config-wantedly:
- changed-files:
  - any-glob-to-any-file: packages/prettier-config-wantedly/**/*
