module.exports = {
  env: {
    browser: true,
    es6: true,
    "jest/globals": true,
  },
  globals: {
    flushPromises: true, // see: jestEnvironment.js
  },
  extends: "airbnb",
  parser: "babel-eslint",
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
    sourceType: "module",
  },
  plugins: ["react", "jest"],
  rules: {
    "arrow-body-style": ["off"],
    "class-methods-use-this": "warn",
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "never",
      },
    ],
    "linebreak-style": ["error", "unix"],
    quotes: ["off"],
    "jsx-quotes": ["off"],
    semi: ["error", "always"],
    "no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
      },
    ],
    "no-underscore-dangle": ["off"],
    "react/jsx-uses-vars": "error",
    "react/forbid-prop-types": "off",
    "react/no-unused-prop-types": "warn",
    "new-cap": [
      "error",
      {
        capIsNew: false,
      },
    ],
    "max-len": ["off"],
    "no-plusplus": [
      "error",
      {
        allowForLoopAfterthoughts: true,
      },
    ],
    "jsx-no-target-blank": "off",
    "generator-star-spacing": ["off"],
    "no-alert": "off",
    "no-shadow": "off",
    "no-use-before-define": [
      "warn",
      {
        functions: false,
      },
    ],
    "import/no-extraneous-dependencies": ["off"],
    "import/no-unresolved": ["off"],
    "import/prefer-default-export": "off",
    "arrow-parens": ["warn", "as-needed"],
    "react/require-default-props": "warn",
    "import/first": "warn",
    "react/jsx-no-bind": "warn",
    "jsx-a11y/no-static-element-interactions": "warn",
    "react/prop-types": "warn",
    "react/jsx-indent": "warn",
    "jsx-a11y/alt-text": "warn",
    "react/jsx-wrap-multilines": "warn",
    "react/no-array-index-key": "warn",
    "jsx-a11y/no-noninteractive-element-interactions": "warn",
    "no-else-return": "warn",
    "react/jsx-indent-props": "warn",
    "react/jsx-closing-bracket-location": "warn",
    "consistent-return": "warn",
    "react/no-string-refs": "warn",
    "react/jsx-filename-extension": "warn",
    "prefer-const": "warn",
    eqeqeq: "warn",
    "react/jsx-no-target-blank": "warn",
    "import/extensions": "off",
    "no-useless-constructor": "warn",
    indent: "warn",
    "react/no-find-dom-node": "warn",
    "no-mixed-operators": "warn",
    "jsx-a11y/label-has-for": "warn",
    "dot-notation": "warn",
    "no-extra-boolean-cast": "warn",
    "no-lonely-if": "warn",
    "prefer-template": "warn",
    "no-nested-ternary": "warn",
    "no-undef": "warn",
    "space-before-function-paren": "warn",
    "react/jsx-no-duplicate-props": "warn",
    "quote-props": "warn",
    "react/no-multi-comp": "warn",
    "object-shorthand": "warn",
    "array-callback-return": "warn",
    "no-param-reassign": "warn",
    "no-useless-escape": "warn",
    "jsx-a11y/href-no-hash": "warn",
    "react/no-did-update-set-state": "warn",
    "no-cond-assign": "warn",
  },
};
