module.exports = {
  env: {
    browser: true,
    es6: true,
    "jest/globals": true,
    node: true,
  },
  globals: {
    flushPromises: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:@typescript-eslint/recommended",
    "prettier",
    "prettier/@typescript-eslint",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
    sourceType: "module",
  },
  plugins: ["react", "import", "jsx-a11y", "jest", "prettier", "@typescript-eslint"],
  rules: {
    "array-callback-return": "warn",
    "arrow-body-style": ["off"],
    "arrow-parens": ["warn", "as-needed"],
    "class-methods-use-this": "warn",
    "comma-dangle": [
      "error",
      {
        arrays: "always-multiline",
        objects: "always-multiline",
        imports: "always-multiline",
        exports: "always-multiline",
        functions: "never",
      },
    ],
    "consistent-return": "warn",
    "dot-notation": "warn",
    "generator-star-spacing": ["off"],
    "jsx-no-target-blank": "off",
    "jsx-quotes": ["off"],
    "linebreak-style": ["error", "unix"],
    "max-len": ["off"],
    "new-cap": ["error", { capIsNew: false }],
    "no-alert": "off",
    "no-array-constructor": "error",
    "no-cond-assign": "warn",
    "no-else-return": "warn",
    "no-extra-boolean-cast": "warn",
    "no-lonely-if": "warn",
    "no-mixed-operators": "warn",
    "no-nested-ternary": "warn",
    "no-param-reassign": "warn",
    "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
    "no-shadow": "off",
    "no-undef": "warn",
    "no-underscore-dangle": ["off"],
    "no-unused-vars": ["error", { varsIgnorePattern: "^_", argsIgnorePattern: "^_" }],
    "no-use-before-define": ["warn", { functions: false }],
    "no-useless-constructor": "warn",
    "no-useless-escape": "warn",
    "object-shorthand": "warn",
    "prefer-const": "warn",
    "prefer-template": "warn",
    "quote-props": ["warn", "as-needed"],
    "space-before-function-paren": [
      "warn",
      {
        anonymous: "always",
        asyncArrow: "always",
        named: "never",
      },
    ],
    camelcase: ["error", { ignoreDestructuring: false, properties: "never" }],
    eqeqeq: "warn",
    indent: ["error", 2],
    quotes: ["off"],
    semi: ["error", "always"],

    // @typescript-eslint/eslint-plugin rules
    "@typescript-eslint/explicit-function-return-type": ["off"],
    "@typescript-eslint/no-explicit-any": ["off"],
    "@typescript-eslint/indent": ["error", 2],
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        varsIgnorePattern: "^_",
        argsIgnorePattern: "^_",
      },
    ],

    // eslint-plugin-import rules
    "import/extensions": "off",
    "import/first": "warn",
    "import/no-extraneous-dependencies": ["off"],
    "import/no-unresolved": ["off"],
    "import/prefer-default-export": "off",

    // eslint-plugin-jsx-a11y rules
    "jsx-a11y/alt-text": "warn",
    "jsx-a11y/label-has-for": "warn",
    "jsx-a11y/no-noninteractive-element-interactions": "warn",
    "jsx-a11y/no-static-element-interactions": "warn",

    // eslint-plugin-react rules
    "react/forbid-prop-types": "off",
    "react/jsx-closing-bracket-location": "warn",
    "react/jsx-filename-extension": "warn",
    "react/jsx-indent-props": "warn",
    "react/jsx-indent": "warn",
    "react/jsx-no-bind": "warn",
    "react/jsx-no-duplicate-props": "warn",
    "react/jsx-no-target-blank": "warn",
    "react/jsx-uses-vars": "error",
    "react/jsx-wrap-multilines": "warn",
    "react/no-array-index-key": "warn",
    "react/no-did-update-set-state": "warn",
    "react/no-find-dom-node": "warn",
    "react/no-multi-comp": "warn",
    "react/no-string-refs": "warn",
    "react/no-unused-prop-types": "warn",
    "react/prop-types": "warn",
    "react/require-default-props": "warn",
  },
};
