version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: Run Lint
          command: yarn lint

      - run:
          name: Run Test
          command: yarn test

jobs:
  node-v10:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - test-nodejs
  node-v12:
    docker:
      - image: node:12
    working_directory: ~/repo
    steps:
      - test-nodejs
  node-v13:
    docker:
      - image: node:13
    working_directory: ~/repo
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v13
